:bug: Fix missing change to asyncio.get_running_loop()
This fixes
```
    File "/home/tux/DesktopPanel/amqp.py", line 241, in _on_connection_closed
      self._connection.ioloop.call_later(5, self._reconnect)
  AttributeError: 'NoneType' object has no attribute 'ioloop'
```